reverted release script, added CVE check to java build

diff --git a/.github/workflows/java-release.yml b/.github/workflows/java-release.yml
--- a/.github/workflows/java-release.yml
+++ b/.github/workflows/java-release.yml
@@ -1,133 +1,96 @@
-name: CI-java
+name: Publish New Java Release
 on:
-  pull_request:
-  workflow_call:
-    inputs:
-      version:
-        required: true
-        type: string
-    outputs:
-      modules:
-        description: "Stream reactor collection of modules"
-        value: ${{ jobs.initiate.outputs.matrix }}
+  push:
+    tags:
+      - "*"
+  workflow_dispatch:
 
 jobs:
-
-  initiate:
-    timeout-minutes: 5
+  validate-tag:
     runs-on: ubuntu-latest
     outputs:
-      matrix: ${{ steps.java-mods.outputs.matrix }}
+      draft_release: ${{ steps.get_tag.outputs.draft_release }}
+      tag: ${{ steps.get_tag.outputs.tag }}
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 17
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Get tag, release mode
+        shell: bash
+        id: get_tag
+        run: |
+          if [[ ${GITHUB_REF##*/} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]];
+          then
+              draft_release=false
+          
+          elif [[ ${GITHUB_REF##*/} =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(\.[0-9]+)?)?(\+[A-Za-z0-9.]+)?$ ]];
+          then
+              draft_release=true
+          else
+              echo "Exiting, github ref needs to be a tag with format x.y.z or x.y.z-(alpha|beta|rc)"
+              exit 1
+          fi
+          echo "::set-output name=draft_release::$draft_release"
+          echo "::set-output name=tag::${GITHUB_REF##*/}"
+
+  build:
+    needs:
+      - validate-tag
+    uses: ./.github/workflows/java-build.yml
+    with:
+      version: ${{ needs.validate-tag.outputs.tag }}
+    secrets: inherit
+
+  create-release:
+    runs-on: ubuntu-latest
+    needs:
+      - validate-tag
+      - build
+    strategy:
+      # Avoid parallel uploads
+      max-parallel: 1
+      # GitHub will NOT cancel all in-progress and queued jobs in the matrix if any job in the matrix fails, which could create inconsistencies.
+      # If any matrix job fails, the job will be marked as failure
+      fail-fast: false
+      matrix:
+        module: ${{fromJSON(needs.build.outputs.modules)}}
+    env:
+      DRAFT_RELEASE: '${{ needs.validate-tag.outputs.draft_release }}'
+      TAG: ${{ needs.validate-tag.outputs.tag }}
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
-          java-version: '17'
+          java-version: '21'
           distribution: 'temurin'
           cache: 'gradle'
-      - name: Generate modules lists
-        run: cd 'java-connectors' && ./gradlew releaseModuleList
-        env:
-          JVM_OPTS: -Xmx512m
-      - name: Read java modules lists
-        id: java-mods
-        run: |
-          echo "::set-output name=matrix::$(cat ./java-connectors/gradle-modules.txt)"
 
-  test:
-    needs:
-      - initiate
-    strategy:
-      matrix:
-        module: ${{fromJSON(needs.initiate.outputs.matrix)}}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
+      - name: Uncache assembly
+        uses: actions/cache/restore@v4
         with:
-          java-version: 17
-          distribution: 'temurin'
+          path: |
+            ./java-connectors/release/${{ matrix.module }}*.jar
+          key: assembly-java-${{ github.run_id }}
+          fail-on-cache-miss: true
 
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3
-        with:
-          gradle-version: 8.6
-
-      - name: Test with Gradle
-        run: cd 'java-connectors' && ./gradlew ${{ matrix.module }}:test
-
-  build-and-dependency-check:
-    needs:
-      - test
-      - initiate
-    strategy:
-      matrix:
-        module: ${{fromJSON(needs.initiate.outputs.matrix)}}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'temurin'
-          cache: gradle
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3
-        with:
-          gradle-version: 8.6
-
-      - name: Execute Gradle build
-        run: cd 'java-connectors' && ./gradlew ${{ matrix.module }}:shadowJar --scan
-
-      - name: Move to release folder
+      - name: Package Connector
         shell: bash
         run: |
           JAVA_RELEASE_FOLDER=java-connectors/release
-          JAVA_BUILD_FOLDER=java-connectors/${{ matrix.module }}/build/libs
-          mkdir -p $JAVA_RELEASE_FOLDER
-          cp $JAVA_BUILD_FOLDER/${{ matrix.module }}*.jar LICENSE $JAVA_RELEASE_FOLDER/
+          FOLDER=${{ matrix.module }}-${{ env.TAG }}
+          mkdir -p $FOLDER
+          cp $JAVA_RELEASE_FOLDER/${{ matrix.module }}*.jar LICENSE $FOLDER/
+          zip -r "$FOLDER.zip" $FOLDER/
 
-      - name: Cache assembly
-        uses: actions/cache/save@v4
+      - name: Upload binaries to release
+        uses: svenstaro/upload-release-action@v2
         with:
-          path: ./java-connectors/release/${{ matrix.module }}*.jar
-          key: assembly-java-${{ github.run_id }}
-
-  jar-dependency-check:
-    needs:
-      - build-and-dependency-check
-      - initiate
-    timeout-minutes: 30
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        module: ${{fromJSON(needs.initiate.outputs.matrix)}}
-    steps:
-      - name: Restore assembly
-        uses: actions/cache/restore@v4
-        with:
-          path: ~/**/target/libs/*.jar
-          key: assembly-java-${{ github.run_id }}
-          fail-on-cache-miss: true
-      - name: Get branch names.
-        id: branch_name
-        uses: tj-actions/branch-names@v8
-      - name: Dependency Check
-        uses: dependency-check/Dependency-Check_Action@main
-        with:
-          project: kafka-connect-${{matrix.module}}-deps
-          path: kafka-connect-${{matrix.module}}/target/libs/
-          format: 'HTML'
-          args: >-
-            --failOnCVSS 5
-            --suppression https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.owner.login }}/${{github.event.repository.name}}/${{ steps.branch_name.outputs.tag }}${{ steps.branch_name.outputs.current_branch }}/suppression.xml
-      - name: Upload Test results
-        uses: actions/upload-artifact@master
-        with:
-          name: ${{matrix.module}}-depcheck-results
-          path: ${{github.workspace}}/reports
+          file: ${{ matrix.module }}-${{ env.TAG }}.zip
+          asset_name: "${{ matrix.module }}-${{ env.TAG }}.zip"
+          release_name: 'Stream Reactor ${{ env.TAG }}'
+          prerelease: ${{ env.DRAFT_RELEASE }}
